#!/bin/sh -e

CURRENT_DIR=$PWD
TYPES_PARENT_DIR=external_types

pack() {
	npm --pack-destination=/tmp pack
}

download_pkg() {
	base_url=https://raw.githubusercontent.com/$1/master/$2
	endpoint_path=/repos/$1/contents/$2
	types_dir=$TYPES_PARENT_DIR/${1##*/}

	mkdir -p "$types_dir"
	cd "$types_dir"

	for i in $(gh api --jq '.[].name' "$endpoint_path"); do
		curl -s -o "$i" "$base_url/$i"
	done

	if ! pack; then
		# wtf?
		path=package.json
		c=$(cat "$path")

		printf '{ "name": "@types/gecko", "version": "1.0.0", %s' "${c#'{'}" > "$path"
		pack
	fi

	cd "$CURRENT_DIR"
}

download_pkg mozilla/gecko-dev tools/@types
download_pkg MrOtherGuy/fx-autoconfig types