#!/bin/sh

for file in types/mpd/*.d.ts; do
	while read -r line; do
		case $line in
			'export enum'* | 'export interface'*) ;;
			*) continue
		esac

		file=${file##*/}
		file=${file%.*}
		type=${line#export enum}
		type=${type#export interface}
		type=${type%' {'}

		printf 'import type { %s } from "./%s";\n' "$type" "$file"
	done < "$file"
done
